# .pre-commit-config.yaml
repos:
- repo: local
  hooks:
  - id: black
    name: Black
    entry: black --line-length 99
    exclude: ^app/alembic/
    language: python
    types: [python]
- repo: local
  hooks:
  - id: flake8
    name: Flake
    entry: flake8  --max-line-length 99
    exclude: ^app/alembic/
    language: system
    types: [python]
