"""create vacation table

Revision ID: 07152978ca94
Revises: 9b69732bce67
Create Date: 2023-09-09 14:34:16.207372

"""
from alembic import op
import sqlalchemy as sa

from app.model.base import CustomUUID

# revision identifiers, used by Alembic.
revision = '07152978ca94'
down_revision = '9b69732bce67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation',
    sa.Column('id', CustomUUID(as_uuid=True), nullable=False),
    sa.Column('employee_id', CustomUUID(as_uuid=True), nullable=True),
    sa.Column('type', sa.Enum('PAID', 'UNPAID', name='vacationtypes'), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_id'), 'vacation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacation_id'), table_name='vacation')
    op.drop_table('vacation')
    sa.Enum(name='vacationtypes').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
